apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "looloo.fullname" . }}-kong-config
  labels:
    {{- include "looloo.labels" . | nindent 4 }}
data:
  kong.yml: |
    _format_version: "3.0"
    _transform: true
    services:
      - name: looloo-api
        url: {{ .Values.kong.apiUrl | default (printf "http://%s-api.%s.svc.cluster.local:3000" (include "looloo.fullname" .) .Release.Namespace) | quote }}
        routes:
          - name: looloo-api
            paths:
              - /api
            strip_path: true