apiVersion: v1
kind: Service
metadata:
  name: {{ include "looloo.fullname" . }}-web
  labels:
    {{- include "looloo.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "looloo.fullname" . }}-web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "looloo.fullname" . }}-web
  ports:
    - name: http
      port: 80
      targetPort: http