apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: looloo-api
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames:
      - looloo
  selector:
    matchLabels:
      app.kubernetes.io/name: looloo-api
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s